# Backend de colores (prueba kmeans, colorz, wal, vibrant)
backend = "kmeans"

# Espacio de color
color_space = "labmixed"

# (dark, light, amoled, etc)
palette = "dark16"

threshold = 11

[templates]

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/themes/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

hyprLua.template = 'colors-hyprland.lua'
hyprLua.target = '~/.config/hypr/modules/colors.lua'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/colors.css'

keyboard.template = "colors-keyboard.txt"
keyboard.target = "~/.cache/wallust/keyboard-colors"

quickshell.template = "colors-quickshell.json"
quickshell.target = "~/.cache/wallust/colors.json"

[hooks]
# --reload-css y --reload-config no invalidan el caché de @import de GTK
reload_swaync = "pkill -x swaync; sleep 0.5; swaync &"
