# Backend de colores (prueba kmeans, colorz, wal, vibrant)
backend = "kmeans"

# Espacio de color
color_space = "labmixed"

# (dark, light, amoled, etc)
palette = "dark16"

threshold = 11

[templates]

kitty.template = "colors-kitty.conf"
kitty.target = "~/.config/kitty/colors.conf"

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/themes/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/conf/colors.conf'
