foreground         #DBE4DA
background         #000000
cursor             #858F82

active_tab_foreground     #000100
active_tab_background     #DBE4DA
inactive_tab_foreground   #DBE4DA
inactive_tab_background   #000100

active_border_color   #DBE4DA
inactive_border_color #000100
bell_border_color     #232B20

# color0      #000100
# color1		#232B20
# color2		#232B20
# color3		#535B34
# color4		#535B34
# color5		#73856A
# color6		#71866F
# color7		#C3D0C1
# color8		#889287
# color9		#2F392B
# color10		#2F392B
# color11		#6F7946
# color12		#6F7946
# color13		#99B18D
# color14		#97B294
# color15		#C3D0C1
