foreground         #E9EBF7
background         #000000
cursor             #A18CAE

active_tab_foreground     #1B181F
active_tab_background     #E9EBF7
inactive_tab_foreground   #E9EBF7
inactive_tab_background   #1B181F

active_border_color   #E9EBF7
inactive_border_color #1B181F
bell_border_color     #421E46

# color0      #423F47
# color1		#421E46
# color2		#43224B
# color3		#362D88
# color4		#4E4A83
# color5		#545E9F
# color6		#9094AF
# color7		#D7DAEC
# color8		#9698A5
# color9		#58285D
# color10		#592D64
# color11		#483CB5
# color12		#6863AF
# color13		#707ED4
# color14		#C0C5E9
# color15		#D7DAEC
