include colors.conf

# Tema y apariencia
font_family	     JetBrainsMono Nerd Font
font_size	     12
bold_font        auto
italic_font      auto
bold_italic_font auto

# altura de linea
line_height 1.15

background_opacity 0.7
dynamic_background_opacity yes

# Copiar solo con seleccionar
copy_on_select yes
strip_trailing_spaces smart

# Espacio de arriba
window_padding_width 10
window_margin_width 5

confirm_os_window_close 0
hide_window_decorations yes

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

# Para que inicie con zsh
shell /usr/bin/zsh
shell_integration enabled


# Otras opciones
enable_wayland_input true
wayland_titlebar_color background


# Para previsualizacion en terminal
allow_remote_control yes
listen_on unix:/tmp/kitty-lf


# Nueva pestaña
map ctrl+shift+t new_tab

# Cerrar pestaña
map ctrl+shift+w close_tab

# Moverse entre pestañas
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
