$background = rgb(27222A)
$foreground = rgb(EFD7DC)

$color0 = rgb(4D4850)
$color1 = rgb(241431)
$color2 = rgb(241431)
$color3 = rgb(5E283E)
$color4 = rgb(5E283E)
$color5 = rgb(544F60)
$color6 = rgb(9D6A75)
$color7 = rgb(E0BEC5)
$color8 = rgb(9C858A)
$color9 = rgb(301A41)
$color10 = rgb(301A41)
$color11 = rgb(7D3552)
$color12 = rgb(7D3552)
$color13 = rgb(706980)
$color14 = rgb(D18E9C)
$color15 = rgb(E0BEC5)
