$background = rgb(121312)
$foreground = rgb(F6EFEB)

$color0 = rgb(3A3B3A)
$color1 = rgb(421C18)
$color2 = rgb(2D3F50)
$color3 = rgb(8B2E2A)
$color4 = rgb(9E332E)
$color5 = rgb(538C77)
$color6 = rgb(AC9D95)
$color7 = rgb(EAE0DA)
$color8 = rgb(A49C99)
$color9 = rgb(582620)
$color10 = rgb(3C546A)
$color11 = rgb(BA3E38)
$color12 = rgb(D2443D)
$color13 = rgb(6EBA9F)
$color14 = rgb(E6D1C6)
$color15 = rgb(EAE0DA)
