$background = rgb(1B181F)
$foreground = rgb(E9EBF7)

$color0 = rgb(423F47)
$color1 = rgb(421E46)
$color2 = rgb(43224B)
$color3 = rgb(362D88)
$color4 = rgb(4E4A83)
$color5 = rgb(545E9F)
$color6 = rgb(9094AF)
$color7 = rgb(D7DAEC)
$color8 = rgb(9698A5)
$color9 = rgb(58285D)
$color10 = rgb(592D64)
$color11 = rgb(483CB5)
$color12 = rgb(6863AF)
$color13 = rgb(707ED4)
$color14 = rgb(C0C5E9)
$color15 = rgb(D7DAEC)
