###############
### DEVICES ###
###############

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
device {
    name = instant-usb-gaming-mouse-

    # Sensibilidad y aceleración
    sensitivity = -0.5         # valores -1.0 .. 1.0 (negativo = más lento)

    # Scroll
    scroll_factor = 1.2        # 1.0 normal; >1 aumenta velocidad del scroll
    natural_scroll = false     # false = scroll "tradicional"
}
