#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    # Espacio entre ventanas y bordes, y tamaño del borde
    gaps_in = 5
    gaps_out = 15
    border_size = 2

    # Para cambiar los colores de los bordes XD
    # Para rojo
    #col.active_border = rgba(ff4040ff) rgba(990000ff) 45deg
    #col.inactive_border = rgba(660000ff)

    # Para azul-morado brillante
    #col.active_border = rgba(4c8dffff) rgba(bb44ffff) 45deg
    #col.inactive_border = rgba(2a0f40ff)

    col.active_border = rgba(365faaff) rgba(8a5ccfff) 45deg
    col.inactive_border = rgba(3a2b55ff)


    # Permite cambiar el tamaño de las ventanas haciendo clic
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 8
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.98
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
        new_optimizations = on
    }
}

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    disable_hyprland_logo = true 
}
