plugin {
    hyprexpo {
        columns = 3

        gaps_in = 16
        gaps_out = 28

        bg_col = $background

        workspace_method = center current

        # Labels
        label_enable = true
        label_text_mode = id
        label_font_size = 32

        # Bordes
        border_width = 2
        border_color_current = $color4 $color5 45deg
        border_color_hover = $color6
        border_color_focus = $color3 $color1 45deg

        # Estética
        tile_rounding = 12

        # Iconos
        window_icon_enable = true
        window_icon_position = bottom-right

        # Gestos
        gesture_distance = 180

        cancel_key = escape
    }
}

submap = hyprexpo
    bind = , left,   hyprexpo:kb_focus, left
    bind = , right,  hyprexpo:kb_focus, right
    bind = , up,     hyprexpo:kb_focus, up
    bind = , down,   hyprexpo:kb_focus, down
    bind = , return, hyprexpo:kb_confirm
    bind = , escape, hyprexpo:expo, cancel
    bind = , 1,      hyprexpo:kb_selecti, 1
    bind = , 2,      hyprexpo:kb_selecti, 2
    bind = , 3,      hyprexpo:kb_selecti, 3
    bind = , 4,      hyprexpo:kb_selecti, 4
    bind = , 5,      hyprexpo:kb_selecti, 5
    bind = , 6,      hyprexpo:kb_selecti, 6
    bind = , 7,      hyprexpo:kb_selecti, 7
    bind = , 8,      hyprexpo:kb_selecti, 8
    bind = , 9,      hyprexpo:kb_selecti, 9
    bind = , 0,      hyprexpo:kb_selecti, 10
submap = reset
